language: java
jdk:
 - openjdk11
services:
 #Linking Travis CI and Docker
 - docker
before_install:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker pull openjdk:11-jdk
script: "mvn cobertura:cobertura"
 #We avoid this error :" the job exceeded the maximum log length and has been terminated "
 - echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settingsxsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <mirrors> 
  <mirror>
   <id>mvnsearch-unavailable</id>\n <name>mvnsearch-unavailable</name>\n
   <mirrorOf>mvnsearch</mirrorOf>\n <url>http://repo1.maven.org/maven2</url>\n
  </mirror>
</mirrors>
<profiles>
  <profile>
  <id>no-mvnsearch</id>
<repositories>
<repository>
<id>mvnsearch</id>
<url>http://www.mvnsearch.org/maven2</url>
<releases>
<enabled>true</enabled>
</releases>
<snapshots>
<enabled>true</enabled>
</snapshots>
</repository>
</repositories>
</profile>
</profiles>
<activeProfiles>
<activeProfile>nomvnsearch</activeProfile>
</activeProfiles>
</settings>' > 
$HOME/.m2/settings.xml
 - cat $HOME/.m2/settings.xml
 #deploying the app on Docker
 - mvn deploy
 
 after_success:
 - bash <(curl -s https://codecov.io/bash)
